update shell scripts for tasks
use double quotes for all variables
define SHELL_SETTINGS, sets 'set -o pipefail;shopt -s failglob' in all shell scrips
replace `` with $()
replace 'echo;echo something;read' with 'echo;read -p something'
replace 'echo -n something;read' with 'read -p something'
remove variable \$fm_command, it is just a copy of the current command
remove function write_src_functions(), nothing in spacefm used imported functions

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14508,6 +14508,12 @@ if test ! -z "$bash_path"; then
     sed "s/\(\/bin\/bash\)/$bash_esc/" src/spacefm-auth >| src/spacefm-auth
 fi
 
+#-u is too strict
+cat >>confdefs.h <<_ACEOF
+#define SHELL_SETTINGS "set -o pipefail\nshopt -s failglob"
+_ACEOF
+
+
 # gtk2 or gtk3
 
 
